# Generated by Django 4.2.11 on 2026-05-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("paragraphs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wordfrequency",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="paragraph",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="wordfrequency",
            index=models.Index(
                fields=["user", "word"], name="paragraphs__user_id_b96856_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wordfrequency",
            unique_together={("user", "paragraph", "word")},
        ),
    ]
